# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:09:15+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Header

from models import (
    Certs,
    DataNotification,
    ErrorResponse,
    HealthInformationNotification,
    HeartbeatResponse,
    HIPConsentNotification,
    HIPConsentNotificationResponse,
    HIPHealthInformationRequest,
    HIPHealthInformationRequestAcknowledgement,
    LinkConfirmationRequest,
    OpenIdConfiguration,
    PatientAuthConfirmRequest,
    PatientAuthConfirmResponse,
    PatientAuthInitRequest,
    PatientAuthInitResponse,
    PatientAuthModeQueryRequest,
    PatientAuthModeQueryResponse,
    PatientAuthNotification,
    PatientAuthNotificationAcknowledgement,
    PatientCareContextLinkRequest,
    PatientCareContextLinkResponse,
    PatientDiscoveryRequest,
    PatientDiscoveryResult,
    PatientLinkReferenceRequest,
    PatientLinkReferenceResult,
    PatientLinkResult,
    PatientSMSNotifcationRequest,
    PatientSMSNotifcationResponse,
    SessionRequest,
    SessionResponse,
    ShareProfileRequest,
    ShareProfileResult,
)

app = MCPProxy(
    contact={'name': 'National Health Authority', 'url': 'https://ndhm.gov.in/'},
    description='The following are the specifications for the APIs to be implemented at the Health Repository end if an entity is only serving the role of a HIP. The specs are essentially duplicates from the Gateway and Health Repository, but put together so as to make it clear to *HIPs* which set of APIs they should implement to participate in the network. \n',
    title='Health Repository Provider Specifications for HIP',
    version='0.5',
    servers=[{'description': 'Sandbox', 'url': 'https://dev.ndhm.gov.in/gateway'}],
)


@app.get('/v0.5/.well-known/openid-configuration', tags=['openid_configuration'])
def get_v0_5__well_known_openid_configuration():
    """
    Get openid configuration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/care-contexts/discover',
    description=""" Request for patient care context discover, made by Gateway intended for a specific HIP. It is expected that HIP will subsequently return either zero or one patient record with (potentially masked) associated care contexts
  1. **At least one of the verified identifier matches**
  2. **Name (fuzzy), gender matches**
  3. **If YoB was given, age band(+-2) matches**
  4. **If unverified identifiers were given, one of them matches**
  5. **If more than one patient records would be found after aforementioned steps, then patient who matches most verified and unverified identifiers would be returned.**
  6. **If there would be still more than one patients (after ranking) error would be returned**
  7. **Intended HIP should be able to resolve and identify results returned in the subsequent link confirmation request via the specified transactionId**
  8. **Intended HIP should store the discovery results with transactionId and care contexts discovered for subsequent link initiation**
 """,
    tags=['patient_account_discovery'],
)
def post_v0_5_care_contexts_discover(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: PatientDiscoveryRequest = ...,
):
    """
    Discover patient's accounts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/care-contexts/on-discover',
    description=""" Result of patient care-context discovery request at HIP end. If a matching patient found with zero or more care contexts associated, it is specified as result attribute. If the prior discovery request, resulted in errors then it is specified in the error attribute. Reasons of errors can be 
  1. **more than one definitive match for the given request** 
  2. **no verified identifer was specified**
 """,
    tags=['patient_account_discovery', 'health_information_request_processing'],
)
def post_v0_5_care_contexts_on_discover(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientDiscoveryResult = ...,
):
    """
    Response to patient's account discovery request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v0.5/certs', tags=['user_authentication_services'])
def get_v0_5_certs():
    """
    Get certs for JWT verification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consents/hip/notify',
    description=""" Notification of consents to health information providers consent request granted, consent revoked, consent expired. Only the GRANTED and REVOKED status notifications will be sent to HIP.
  1. If consent is granted, status=GRANTED, then consentDetail contains the consent artefact details and signature is available. 
  2. If consent is revoked, then status=REVOKED, and consentId specifes which consent artefact is revoked. 
 """,
    tags=['consent_management_notifications'],
)
def post_v0_5_consents_hip_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: HIPConsentNotification = ...,
):
    """
    Consent notification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consents/hip/on-notify',
    description=""" This API is called by HIP as acknowledgement to notification of consents, in cases of consent revocation and expiration. 
 """,
    tags=['consent_management_notifications'],
)
def post_v0_5_consents_hip_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: HIPConsentNotificationResponse = ...,
):
    """
    Consent notification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/health-information/hip/on-request',
    description=""" API called by HIP to acknowledge Health information request receipt. Either the **hiRequest** or **error** must be specified. **hiRequest** element returns the same transactionId as before with a status indicating that the request is acknowledged.  
 """,
    tags=['health_information_request_processing'],
)
def post_v0_5_health_information_hip_on_request(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: HIPHealthInformationRequestAcknowledgement = ...,
):
    """
    Health information data request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/health-information/hip/request',
    description=""" API called by CM to request Health information from HIP against a validated consent artefact. The transactionId is the correlation id that HIP should use use when pushing data to the **dataPushUrl**. 
 """,
    tags=['health_information_request_processing', 'patient_profile_handling'],
)
def post_v0_5_health_information_hip_request(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: HIPHealthInformationRequest = ...,
):
    """
    Health information data request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/health-information/notify',
    description=""" API called by HIU and HIP during data-transfer. 
1. HIP on transfer of data would send **sessionStatus** - one of [TRANSFERRED, FAILED]
2. HIP would also send **hiStatus** for each *careContextReference* - on of [DELIVERED, ERRORED]
3. HIU on receipt of data would send **sessionStatus** - one of [TRANSFERRED, FAILED]. For example, FAILED when if data was not sent or if invalid data was sent
4. HIU would also send **hiStatus** for each *careContextReference* - one of [OK, ERRORED] 
 """,
    tags=['health_information_event_notifications'],
)
def post_v0_5_health_information_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: HealthInformationNotification = ...,
):
    """
    Notifications corresponding to events during data flow
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/health-information/transfer',
    description=""" **NOTE**: This API is actually the callback URL that is passed as **dataPushUrl** in the data request API - /v0.5/health-information/hip/request. This API is directly called by HIP Data Bridge and is not mediated via CM, and hence not routed through the Gateway. 
  1. This API should be implemented at HIU side. It maybe implemented by the Data Bridge representing the HIU. 
  2. Entry elements maybe ***content*** or ***link***, although for version 1, entry ***content*** is preferred. 
  3. Entry ***content*** (or even link reference content) must be encrypted by means of Elliptic-curve Diffie–Hellman Key Exchange, utilizing the HIU keymaterials that are passed through the data request API - /v0.5/health-information/hip/request. 
  4. Media contains the mimetype of content, and for v1, it is "application/fhir+json"
  5. checksum is Md5 checksum of the data conent, before encryption
  6. Please refer to the NDHM Sandbox Documentation for the format of FHIR bundle that is passed through content 
 """,
    tags=[
        'health_information_event_notifications',
        'health_information_request_processing',
        'consent_management_notifications',
    ],
)
def post_v0_5_health_information_transfer(
    authorization: str = Header(..., alias='Authorization'),
    body: DataNotification = ...,
):
    """
    health information transfer API
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v0.5/heartbeat', tags=['consent_management_notifications'])
def get_v0_5_heartbeat():
    """
    Get consent request status
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/add-contexts',
    description=""" API to submit care-context to CM for HIP initiated linking. The API must accompany the "accessToken" fetched in the users/auth process.  
  1. subsequent usage for accessToken may be invalid if it was meant for one-time usage or if it expired
 """,
    tags=['care_context_management', 'health_information_request_processing'],
)
def post_v0_5_links_link_add_contexts(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientCareContextLinkRequest = ...,
):
    """
    API for HIP initiated care-context linking for patient
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/confirm',
    description=""" API to submit the token that was sent by HIP during the link request. 
 """,
    tags=['consent_management_notifications', 'care_context_management'],
)
def post_v0_5_links_link_confirm(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: LinkConfirmationRequest = ...,
):
    """
    Token submission by Consent Manager for link confirmation
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/init',
    description=""" Request from Gateway to links care contexts associated with only one patient
  1. **Validate account reference number and care context reference number**
  2. **Validate transactionId in the request with discovery request entry to check whether there was a discovery
      and were these care contexts discovered or not for a given patient**
  3. **Before eventual link confirmation, HIP needs to authenticate the request with the patient(eg: OTP verification)**
  4. **HIP should communicate the mode of authentication of a successful request to Consent Manager**
 """,
    tags=['care_context_management', 'patient_account_discovery'],
)
def post_v0_5_links_link_init(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: PatientLinkReferenceRequest = ...,
):
    """
    Link patient's care contexts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/on-add-contexts',
    description=""" If the accessToken is valid for purpose of linking, and specified details provided, CM will send "acknoweldgement.status" as SUCCESS. If any error occcurred, for example invalid token, or other required patient or care-context information not provided, then "error" attribute conveys so. 
  1. **accessToken must be valid and must be for the purpose of linking**
 """,
    tags=['care_context_management', 'patient_account_discovery'],
)
def post_v0_5_links_link_on_add_contexts(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: PatientCareContextLinkResponse = ...,
):
    """
    callback API for HIP initiated patient linking /link/add-context
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/on-confirm',
    description=""" Returns a list of linked care contexts with patient reference number.
  1. **Validated and linked account reference number**
  2. **Validated that the token sent from Consent Manager is same as the one generated by HIP**
  3. **Verified that same Consent Manager which made the link request is sending the token**
  4. **Results of unmasked linked care contexts with patient reference number**
 """,
    tags=['care_context_management', 'health_information_event_notifications'],
)
def post_v0_5_links_link_on_confirm(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientLinkResult = ...,
):
    """
    Token authenticated by HIP, indicating completion of linkage of care-contexts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/on-init',
    description=""" Result of patient care-context link request from HIP end. This happens in context of previous discovery of patient found at HIP end, therefore the link requests ought to be in reference to the patient reference and care-context references previously returned by the HIP. The correlation of discovery and link request is maintained through the transactionId. HIP should have
  1. **Validated transactionId in the request to check whether there was a discovery done previously, and the link request corresponds to returned patient care care context references**
  2. **Before returning the response, HIP should have sent an authentication request to the patient(eg: OTP verification)**
  3. **HIP should communicate the mode of authentication of a successful request**
  4. **HIP subsequently should expect the token passed via /link/confirm against the link.referenceNumber passed in this call**




















  
The error section in the body, represents the potential errors that may have occurred. Possible reasons:
  1. **Patient reference number is invalid**
  2. **Care context reference numbers are invalid**
 """,
    tags=['care_context_management', 'patient_account_discovery'],
)
def post_v0_5_links_link_on_init(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientLinkReferenceResult = ...,
):
    """
    Response to patient's care context link request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/patients/profile/on-share',
    description=""" Result of patient share profile request at HIP end.
 """,
    tags=['patient_profile_handling', 'patient_account_discovery'],
)
def post_v0_5_patients_profile_on_share(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: ShareProfileResult = ...,
):
    """
    Response to patient's share profile request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/patients/profile/share',
    description=""" Request for sharing patient's profile details to HIP
 """,
    tags=['patient_profile_handling'],
)
def post_v0_5_patients_profile_share(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: ShareProfileRequest = ...,
):
    """
    Share patient profile details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/patients/sms/notify',
    description=""" API to send SMS notifications to patient with custom deeplink.
 """,
    tags=['sms_notification_services'],
)
def post_v0_5_patients_sms_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientSMSNotifcationRequest = ...,
):
    """
    API for HIP to send SMS notifications to patients
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/patients/sms/on-notify',
    description=""" If the SMS notification is successfully sent to patient then "status" will be "ACKNOWLEDGED" with no error.
If the SMS notification is failed then "status" will be "ERRORED" with error.
 """,
    tags=['sms_notification_services'],
)
def post_v0_5_patients_sms_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: PatientSMSNotifcationResponse = ...,
):
    """
    Acknowledgment response for SMS notification sent to patient by HIP
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/v0.5/sessions', tags=['user_authentication_services'])
def post_v0_5_sessions(body: SessionRequest):
    """
    Get access token
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/confirm',
    description=""" This API is called by HIP/HIUs to confirm authentication of users. The transactionId returned by the previous callback API /users/auth/on-init must be sent. If Authentication is successful the callback API will send an "access token" for subsequent purpose specific API calls. Note only **credential.authCode** or **credential.demographic** should be sent
  1. demographic details are only required for  demographic auth as of now. 
  2. demographic details are required only in MEDIATED cases and if the **auth.mode** so demands. e.g. if **auth.mode** is DEMOGRAPHICS. Usually for demographic authentication, the name, gender and DOB must be exactly as specified in User Account.
  3. demographic.identifier is optional, however maybe required if authentication so mandates. 
  4. credential.authCode is required for other MEDIATED authentication like MOBILE_OTP, AADHAAR_OTP. 
 """,
    tags=['user_authentication_services', 'patient_account_discovery'],
)
def post_v0_5_users_auth_confirm(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientAuthConfirmRequest = ...,
):
    """
    Confirmation request sending token, otp or other authentication details from HIP/HIU for confirmation
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/fetch-modes',
    description=""" This API is meant for identify supported authentication modes for a patient given a specific purpose
 """,
    tags=['user_authentication_services', 'patient_account_discovery'],
)
def post_v0_5_users_auth_fetch_modes(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientAuthModeQueryRequest = ...,
):
    """
    Get a patient's authentication modes relevant to specified purpose
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/init',
    description=""" This API is called by HIPs to initiate authentication of users. A transactionId is retuned by the corresponding callback API for confirmation of user auth.
 """,
    tags=['user_authentication_services'],
)
def post_v0_5_users_auth_init(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientAuthInitRequest = ...,
):
    """
    Initialize authentication from HIP
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/notify',
    description=""" This API is called by CM to confirm authentication of users. The transactionId returned is same as that passed in /auth/on-init. The "auth.status" conveys whether the request was GRANTED or DENIED.

  1. **auth.accessToken** - is specific to the purpose mentioned in the /auth/init. This token needs to be used for initiating the intended action. For example for HIP initiated linking of care-contexts
  2. **NOTE**, only one of **X-HIP-ID** or **X-HIU-ID** will be sent as part of header, not both.
  3. The payload is conditional to the purpose of auth. If purpose specified in /auth/init is KYC or KYC_AND_LINK, then patient details are passed. **auth.accessToken** is passed only if the purpose is LINK or KYC_AND_LINK.
 """,
    tags=['user_authentication_services', 'health_information_event_notifications'],
)
def post_v0_5_users_auth_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: PatientAuthNotification = ...,
):
    """
    notification API in case of DIRECT mode of authentication by the CM
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/on-confirm',
    description=""" This API is called by CM to confirm authentication of users.

  1. **auth.accessToken** - is specific to the purpose mentioned in the /auth/init. This token needs to be used for initiating the intended action. For example for HIP initiated linking of care-contexts
  2. **NOTE**, only one of **X-HIP-ID** or **X-HIU-ID** will be sent as part of header, not both.     
 """,
    tags=['user_authentication_services', 'patient_account_discovery'],
)
def post_v0_5_users_auth_on_confirm(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: PatientAuthConfirmResponse = ...,
):
    """
    callback API for /auth/confirm (in case of MEDIATED auth) to confirm user authentication or not
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/on-fetch-modes',
    description=""" If a patient is found then **auth** attribute contains the supported modes for the specified purpose. 
Otherwise, error is raised for invalid requests or for non-existent id.
Note in addition to the "Authorization" header, one of the following headers must be specified
1. **X-HIU-ID** if the requester is HIU (identified from /auth/fetch-modes requester.id)
2. **X-HIP-ID** if the requester is HIP (identified from /auth/fetch-modes requester.id)
 """,
    tags=['consent_management_notifications', 'user_authentication_services'],
)
def post_v0_5_users_auth_on_fetch_modes(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: PatientAuthModeQueryResponse = ...,
):
    """
    Identification result for a consent-manager user-id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/on-init',
    description=""" If the patient's id is valid, CM will return a transactionId as initialization of user auth. If the request is valid, then 'auth.mode' will convey how the authentication should be done. The authentication can be *mediated* or *direct*. For mediated authentication modes, HIP or HIU is epected to send over relevant code (OTP/token) or demographic info via subsequent API call to /auth/confirm. for direct authentication case, CM will notify requester through/users/auth/notify API. 

  1. **auth.mode** conveys whats the mode of authentication is, and what is expected from HIP/HIU in the subsequent /auth/confirm API call. Possible values 
      1. MOBILE_OTP - auth via OTP to registered mobile. Mediated. 
      2. AADHAAR_OTP - auth initiated with Aadhaar with OTP. Mediated. 
      3. DEMOGRAPHICS - auth initiated with demographic verification
      4. DIRECT - for authentication directly with the patient. e.g. Mobile App, SMS. In this case, the HIP/HIU is not expected to call subsequent /auth/confirm call. CM will do direct authentication with the User (e.g. Mobile App, SMS etc) and will notify requester
  2. **meta.expiry** conveys the expiry time of the token and the authentication session
  3. **NOTE**, only one of **X-HIP-ID** or **X-HIU-ID** will be sent as part of header, not both. 




















  
The error section in the body, represents the potential errors that may have occurred. Possible reasons:
  1. Patient id is invalid
 """,
    tags=['user_authentication_services'],
)
def post_v0_5_users_auth_on_init(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: PatientAuthInitResponse = ...,
):
    """
    Response to user authentication initialization from HIP
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/on-notify',
    description=""" This API is called by HIU/HIPs to confirm acknowledgement for receipt of auth notification is case of DIRECT authentication. 
 """,
    tags=[
        'care_context_management',
        'health_information_event_notifications',
        'consent_management_notifications',
    ],
)
def post_v0_5_users_auth_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientAuthNotificationAcknowledgement = ...,
):
    """
    callback API by HIU/HIPs as acknowledgement of auth notification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
